/* Body file for function Manager
 * Generated by TASTE (kazoo/templates/glue/language_wrappers/vm-if-body/function.tmplt)
 */
#include "manager_vm_if.h"
#include "routing.h"

// Define a global PID variable used to keep track of the sender of the last message
static asn1SccPID sender_pid = PID_env;

// API to provide to the user code the PID of the last PI caller
void manager_get_sender(asn1SccPID *OUT_sender_pid, asn1SccPID unused)
{
  *OUT_sender_pid = sender_pid;
}



extern void CInitmanager(void);

extern void init_samv71asw_timer_manager(void);
extern unsigned samv71asw_timer_manager_initialized;
unsigned manager_initialized = 0;
void init_manager(void)
{
   if (0 == manager_initialized) {
      manager_initialized = 1;
      // Initialize C to call elaboration functions
      CInitmanager();
      // Iterate over all synchronous RIs, and call their parent's
      // init function. Multiple calls are prevented by the "init" guard.
      if (0 == samv71asw_timer_manager_initialized) {
          init_samv71asw_timer_manager();
      }
      manager_initialized = 2;
   }
}
void manager_cooldowntimer(void)
{
   sender_pid = manager_cooldowntimer_get_sender();

   //  Directly call user code, no parameters to pass
   extern void manager_PI_cooldowntimer(void);
   manager_PI_cooldowntimer();
   // puts ("manager_cooldowntimer called");
}




void manager_init(void)
{

   //  Directly call user code, no parameters to pass
   extern void manager_PI_init(void);
   manager_PI_init();
   // puts ("manager_init called");
}




void manager_report_oor(void)
{
   sender_pid = manager_report_oor_get_sender();

   //  Directly call user code, no parameters to pass
   extern void manager_PI_report_oor(void);
   manager_PI_report_oor();
   // puts ("manager_report_oor called");
}

