/* Body file for function Manager
 * Generated by TASTE (kazoo/templates/glue/language_wrappers/vm-if-body/function.tmplt)
 */
#include "manager_vm_if.h"
#include "routing.h"

// Define a global PID variable used to keep track of the sender of the last message
static asn1SccPID sender_pid = PID_env;

// API to provide to the user code the PID of the last PI caller
void manager_get_sender(asn1SccPID *OUT_sender_pid, asn1SccPID unused)
{
  *OUT_sender_pid = sender_pid;
}



extern void CInitmanager(void);

extern void init_demo_timer_manager(void);
extern unsigned demo_timer_manager_initialized;
unsigned manager_initialized = 0;
void init_manager(void)
{
   if (0 == manager_initialized) {
      // Initialize epoch for the MSC tracing in debug mode
      long long unused __attribute__((unused)) = getTimeInMilliseconds();
      manager_initialized = 1;
      // Initialize C to call elaboration functions
      CInitmanager();
      puts ("[TASTE] Initialization completed for function Manager");
      manager_initialized = 2;
   }
}
void manager_cooldowntimer(void)
{
   sender_pid = manager_cooldowntimer_get_sender();
   // In Debug mode and x86 builts only: log MSC data when environment variable is set
   static int innerMsc = -1;
   if (-1 == innerMsc)
     innerMsc = (NULL != getenv("TASTE_INNER_MSC"))?1:0;
   if (1 == innerMsc) {
      long long msc_time = getTimeInMilliseconds();
      printf ("INNER_PI: manager,cooldowntimer,%lld\n", msc_time);
      fflush(stdout);
   }

   //  Directly call user code, no parameters to pass
   extern void manager_PI_cooldowntimer(void);
   manager_PI_cooldowntimer();
   // puts ("manager_cooldowntimer called");
   // trace the SDL state (appears on the MSC)
   if (1 == innerMsc) {
      extern char *manager_state(void);
      printf ("INNER_SDL_STATE: manager,%s\n", manager_state());
      fflush(stdout);
   }
}




void manager_report_oor(void)
{
   sender_pid = manager_report_oor_get_sender();
   // In Debug mode and x86 builts only: log MSC data when environment variable is set
   static int innerMsc = -1;
   if (-1 == innerMsc)
     innerMsc = (NULL != getenv("TASTE_INNER_MSC"))?1:0;
   if (1 == innerMsc) {
      long long msc_time = getTimeInMilliseconds();
      printf ("INNER_PI: manager,report_oor,%lld\n", msc_time);
      fflush(stdout);
   }

   //  Directly call user code, no parameters to pass
   extern void manager_PI_report_oor(void);
   manager_PI_report_oor();
   // puts ("manager_report_oor called");
   // trace the SDL state (appears on the MSC)
   if (1 == innerMsc) {
      extern char *manager_state(void);
      printf ("INNER_SDL_STATE: manager,%s\n", manager_state());
      fflush(stdout);
   }
}

