#ifndef GENERATED_ASN1SCC_dataview_uniq_H
#define GENERATED_ASN1SCC_dataview_uniq_H
/*
Code automatically generated by asn1scc tool
*/
#include "asn1crt.h"
#include "asn1crt_encoding.h"


#ifdef  __cplusplus
extern "C" {
#endif


typedef asn1SccUint asn1SccUInt8T;


flag asn1SccUInt8T_Equal(const asn1SccUInt8T* pVal1, const asn1SccUInt8T* pVal2);

#define ERR_UINT8T		1  /*(0..255)*/
flag asn1SccUInt8T_IsConstraintValid(const asn1SccUInt8T* pVal, int* pErrCode);

#ifdef __cplusplus
extern const asn1SccUInt8T asn1SccUInt8T_constant;
#else
#define asn1SccUInt8T_constant 0UL
#endif

void asn1SccUInt8T_Initialize(asn1SccUInt8T* pVal);

#define ERR_UPER_ENCODE_UINT8T		2  /**/
#define asn1SccUInt8T_REQUIRED_BYTES_FOR_ENCODING       1
#define asn1SccUInt8T_REQUIRED_BITS_FOR_ENCODING        8

flag asn1SccUInt8T_Encode(const asn1SccUInt8T* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints);

#define ERR_UPER_DECODE_UINT8T		3  /**/
flag asn1SccUInt8T_Decode(asn1SccUInt8T* pVal, BitStream* pBitStrm, int* pErrCode);

#define asn1SccUInt8T_REQUIRED_BYTES_FOR_ACN_ENCODING       1
#define asn1SccUInt8T_REQUIRED_BITS_FOR_ACN_ENCODING        8

#define ERR_ACN_ENCODE_UINT8T		4  /**/

flag asn1SccUInt8T_ACN_Encode(const asn1SccUInt8T* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints);

#define ERR_ACN_DECODE_UINT8T		5  /**/
flag asn1SccUInt8T_ACN_Decode(asn1SccUInt8T* pVal, BitStream* pBitStrm, int* pErrCode);
typedef asn1SccUint asn1SccUInt16T;


flag asn1SccUInt16T_Equal(const asn1SccUInt16T* pVal1, const asn1SccUInt16T* pVal2);

#define ERR_UINT16T		6  /*(0..65535)*/
flag asn1SccUInt16T_IsConstraintValid(const asn1SccUInt16T* pVal, int* pErrCode);

#ifdef __cplusplus
extern const asn1SccUInt16T asn1SccUInt16T_constant;
#else
#define asn1SccUInt16T_constant 0UL
#endif

void asn1SccUInt16T_Initialize(asn1SccUInt16T* pVal);

#define ERR_UPER_ENCODE_UINT16T		7  /**/
#define asn1SccUInt16T_REQUIRED_BYTES_FOR_ENCODING       2
#define asn1SccUInt16T_REQUIRED_BITS_FOR_ENCODING        16

flag asn1SccUInt16T_Encode(const asn1SccUInt16T* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints);

#define ERR_UPER_DECODE_UINT16T		8  /**/
flag asn1SccUInt16T_Decode(asn1SccUInt16T* pVal, BitStream* pBitStrm, int* pErrCode);

#define asn1SccUInt16T_REQUIRED_BYTES_FOR_ACN_ENCODING       2
#define asn1SccUInt16T_REQUIRED_BITS_FOR_ACN_ENCODING        16

#define ERR_ACN_ENCODE_UINT16T		9  /**/

flag asn1SccUInt16T_ACN_Encode(const asn1SccUInt16T* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints);

#define ERR_ACN_DECODE_UINT16T		10  /**/
flag asn1SccUInt16T_ACN_Decode(asn1SccUInt16T* pVal, BitStream* pBitStrm, int* pErrCode);
typedef asn1Real asn1SccFloat32;


flag asn1SccFloat32_Equal(const asn1SccFloat32* pVal1, const asn1SccFloat32* pVal2);

#define ERR_FLOAT32		11  /*(-1000..1000)*/
flag asn1SccFloat32_IsConstraintValid(const asn1SccFloat32* pVal, int* pErrCode);

#ifdef __cplusplus
extern const asn1SccFloat32 asn1SccFloat32_constant;
#else
#define asn1SccFloat32_constant 0.0000000000000000000E+000
#endif

void asn1SccFloat32_Initialize(asn1SccFloat32* pVal);

#define ERR_UPER_ENCODE_FLOAT32		12  /**/
#define asn1SccFloat32_REQUIRED_BYTES_FOR_ENCODING       13
#define asn1SccFloat32_REQUIRED_BITS_FOR_ENCODING        104

flag asn1SccFloat32_Encode(const asn1SccFloat32* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints);

#define ERR_UPER_DECODE_FLOAT32		13  /**/
flag asn1SccFloat32_Decode(asn1SccFloat32* pVal, BitStream* pBitStrm, int* pErrCode);

#define asn1SccFloat32_REQUIRED_BYTES_FOR_ACN_ENCODING       13
#define asn1SccFloat32_REQUIRED_BITS_FOR_ACN_ENCODING        104

#define ERR_ACN_ENCODE_FLOAT32		14  /**/

flag asn1SccFloat32_ACN_Encode(const asn1SccFloat32* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints);

#define ERR_ACN_DECODE_FLOAT32		15  /**/
flag asn1SccFloat32_ACN_Decode(asn1SccFloat32* pVal, BitStream* pBitStrm, int* pErrCode);
/*-- asn1SccParameterValue --------------------------------------------*/
/*-- asn1SccParameterValue_val --------------------------------------------*/

typedef enum {
    ParameterValue_val_NONE,
    ParameterValue_val_paramU8_PRESENT,
    ParameterValue_val_paramF_PRESENT
} asn1SccParameterValue_val_selection;

typedef union {
    asn1SccUInt8T paramU8;
    asn1SccFloat32 paramF;
} asn1SccParameterValue_val_unchecked_union;

typedef struct {
    asn1SccParameterValue_val_selection kind;

    asn1SccParameterValue_val_unchecked_union u;
} asn1SccParameterValue_val;
typedef struct {
    asn1SccParameterValue_val val;

} asn1SccParameterValue;

flag asn1SccParameterValue_val_Equal(const asn1SccParameterValue_val* pVal1, const asn1SccParameterValue_val* pVal2);

flag asn1SccParameterValue_Equal(const asn1SccParameterValue* pVal1, const asn1SccParameterValue* pVal2);

#define ERR_PARAMETERVALUE_VAL		38  /**/
#define ERR_PARAMETERVALUE_VAL_PARAMU8_2		23  /**/
#define ERR_PARAMETERVALUE_VAL_PARAMF_2		33  /**/
flag asn1SccParameterValue_val_IsConstraintValid(const asn1SccParameterValue_val* pVal, int* pErrCode);

#define ERR_PARAMETERVALUE		43  /**/
flag asn1SccParameterValue_IsConstraintValid(const asn1SccParameterValue* pVal, int* pErrCode);

#ifdef __cplusplus
extern const asn1SccParameterValue_val asn1SccParameterValue_val_constant;
#else
#define asn1SccParameterValue_val_constant {.kind = ParameterValue_val_paramU8_PRESENT, .u.paramU8 = 0UL}
#endif
#ifdef __cplusplus
extern const asn1SccParameterValue asn1SccParameterValue_constant;
#else
#define asn1SccParameterValue_constant {.val = asn1SccParameterValue_val_constant}
#endif

void asn1SccParameterValue_Initialize(asn1SccParameterValue* pVal);

#define ERR_UPER_ENCODE_PARAMETERVALUE		44  /**/
#define ERR_UPER_ENCODE_PARAMETERVALUE_VAL		39  /**/
#define ERR_UPER_ENCODE_PARAMETERVALUE_VAL_PARAMU8_2		24  /**/
#define ERR_UPER_ENCODE_PARAMETERVALUE_VAL_PARAMF_2		34  /**/
#define asn1SccParameterValue_REQUIRED_BYTES_FOR_ENCODING       14
#define asn1SccParameterValue_REQUIRED_BITS_FOR_ENCODING        105

flag asn1SccParameterValue_Encode(const asn1SccParameterValue* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints);

#define ERR_UPER_DECODE_PARAMETERVALUE		45  /**/
#define ERR_UPER_DECODE_PARAMETERVALUE_VAL		40  /**/
#define ERR_UPER_DECODE_PARAMETERVALUE_VAL_PARAMU8_2		25  /**/
#define ERR_UPER_DECODE_PARAMETERVALUE_VAL_PARAMF_2		35  /**/
flag asn1SccParameterValue_Decode(asn1SccParameterValue* pVal, BitStream* pBitStrm, int* pErrCode);

#define asn1SccParameterValue_REQUIRED_BYTES_FOR_ACN_ENCODING       14
#define asn1SccParameterValue_REQUIRED_BITS_FOR_ACN_ENCODING        105

#define ERR_ACN_ENCODE_PARAMETERVALUE		46  /**/
#define ERR_ACN_ENCODE_PARAMETERVALUE_ID_UNINITIALIZED		47  /**/
#define ERR_ACN_ENCODE_PARAMETERVALUE_ID		16  /**/
#define ERR_ACN_ENCODE_PARAMETERVALUE_VAL		41  /**/
#define ERR_ACN_ENCODE_PARAMETERVALUE_VAL_PARAMU8_2		26  /**/
#define ERR_ACN_ENCODE_PARAMETERVALUE_VAL_PARAMF_2		36  /**/

flag asn1SccParameterValue_ACN_Encode(const asn1SccParameterValue* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints);

#define ERR_ACN_DECODE_PARAMETERVALUE		48  /**/
#define ERR_ACN_DECODE_PARAMETERVALUE_ID		17  /**/
#define ERR_ACN_DECODE_PARAMETERVALUE_VAL		42  /**/
#define ERR_ACN_DECODE_PARAMETERVALUE_VAL_PARAMU8_2		27  /**/
#define ERR_ACN_DECODE_PARAMETERVALUE_VAL_PARAMF_2		37  /**/
flag asn1SccParameterValue_ACN_Decode(asn1SccParameterValue* pVal, BitStream* pBitStrm, int* pErrCode);
typedef flag asn1SccFlag8;


flag asn1SccFlag8_Equal(const asn1SccFlag8* pVal1, const asn1SccFlag8* pVal2);

#define ERR_FLAG8		49  /**/
flag asn1SccFlag8_IsConstraintValid(const asn1SccFlag8* pVal, int* pErrCode);

#ifdef __cplusplus
extern const asn1SccFlag8 asn1SccFlag8_constant;
#else
#define asn1SccFlag8_constant FALSE
#endif

void asn1SccFlag8_Initialize(asn1SccFlag8* pVal);

#define ERR_UPER_ENCODE_FLAG8		50  /**/
#define asn1SccFlag8_REQUIRED_BYTES_FOR_ENCODING       1
#define asn1SccFlag8_REQUIRED_BITS_FOR_ENCODING        1

flag asn1SccFlag8_Encode(const asn1SccFlag8* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints);

#define ERR_UPER_DECODE_FLAG8		51  /**/
flag asn1SccFlag8_Decode(asn1SccFlag8* pVal, BitStream* pBitStrm, int* pErrCode);

#define asn1SccFlag8_REQUIRED_BYTES_FOR_ACN_ENCODING       1
#define asn1SccFlag8_REQUIRED_BITS_FOR_ACN_ENCODING        1

#define ERR_ACN_ENCODE_FLAG8		52  /**/

flag asn1SccFlag8_ACN_Encode(const asn1SccFlag8* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints);

#define ERR_ACN_DECODE_FLAG8		53  /**/
flag asn1SccFlag8_ACN_Decode(asn1SccFlag8* pVal, BitStream* pBitStrm, int* pErrCode);
typedef enum {
    ParameterID_paramU8 = 1,
    ParameterID_paramF = 2
} asn1SccParameterID;

// please use the following macros to avoid breaking code.
#define asn1SccParameterID_paramU8 ParameterID_paramU8
#define asn1SccParameterID_paramF ParameterID_paramF

flag asn1SccParameterID_Equal(const asn1SccParameterID* pVal1, const asn1SccParameterID* pVal2);

#define ERR_PARAMETERID		54  /*paramU8 | paramF*/
flag asn1SccParameterID_IsConstraintValid(const asn1SccParameterID* pVal, int* pErrCode);

#ifdef __cplusplus
extern const asn1SccParameterID asn1SccParameterID_constant;
#else
#define asn1SccParameterID_constant ParameterID_paramU8
#endif

void asn1SccParameterID_Initialize(asn1SccParameterID* pVal);

#define ERR_UPER_ENCODE_PARAMETERID		55  /**/
#define asn1SccParameterID_REQUIRED_BYTES_FOR_ENCODING       1
#define asn1SccParameterID_REQUIRED_BITS_FOR_ENCODING        1

flag asn1SccParameterID_Encode(const asn1SccParameterID* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints);

#define ERR_UPER_DECODE_PARAMETERID		56  /**/
flag asn1SccParameterID_Decode(asn1SccParameterID* pVal, BitStream* pBitStrm, int* pErrCode);

#define asn1SccParameterID_REQUIRED_BYTES_FOR_ACN_ENCODING       1
#define asn1SccParameterID_REQUIRED_BITS_FOR_ACN_ENCODING        1

#define ERR_ACN_ENCODE_PARAMETERID		57  /**/

flag asn1SccParameterID_ACN_Encode(const asn1SccParameterID* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints);

#define ERR_ACN_DECODE_PARAMETERID		58  /**/
flag asn1SccParameterID_ACN_Decode(asn1SccParameterID* pVal, BitStream* pBitStrm, int* pErrCode);
typedef asn1SccSint asn1SccT_Int32;


flag asn1SccT_Int32_Equal(const asn1SccT_Int32* pVal1, const asn1SccT_Int32* pVal2);

#define ERR_T_INT32		59  /*(-2147483648 .. 2147483647)*/
flag asn1SccT_Int32_IsConstraintValid(const asn1SccT_Int32* pVal, int* pErrCode);

#ifdef __cplusplus
extern const asn1SccT_Int32 asn1SccT_Int32_constant;
#else
#define asn1SccT_Int32_constant 0LL
#endif

void asn1SccT_Int32_Initialize(asn1SccT_Int32* pVal);

#define ERR_UPER_ENCODE_T_INT32		60  /**/
#define asn1SccT_Int32_REQUIRED_BYTES_FOR_ENCODING       4
#define asn1SccT_Int32_REQUIRED_BITS_FOR_ENCODING        32

flag asn1SccT_Int32_Encode(const asn1SccT_Int32* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints);

#define ERR_UPER_DECODE_T_INT32		61  /**/
flag asn1SccT_Int32_Decode(asn1SccT_Int32* pVal, BitStream* pBitStrm, int* pErrCode);

#define asn1SccT_Int32_REQUIRED_BYTES_FOR_ACN_ENCODING       4
#define asn1SccT_Int32_REQUIRED_BITS_FOR_ACN_ENCODING        32

#define ERR_ACN_ENCODE_T_INT32		62  /**/

flag asn1SccT_Int32_ACN_Encode(const asn1SccT_Int32* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints);

#define ERR_ACN_DECODE_T_INT32		63  /**/
flag asn1SccT_Int32_ACN_Decode(asn1SccT_Int32* pVal, BitStream* pBitStrm, int* pErrCode);
typedef asn1SccUint asn1SccT_UInt32;


flag asn1SccT_UInt32_Equal(const asn1SccT_UInt32* pVal1, const asn1SccT_UInt32* pVal2);

#define ERR_T_UINT32		64  /*(0 .. 4294967295)*/
flag asn1SccT_UInt32_IsConstraintValid(const asn1SccT_UInt32* pVal, int* pErrCode);

#ifdef __cplusplus
extern const asn1SccT_UInt32 asn1SccT_UInt32_constant;
#else
#define asn1SccT_UInt32_constant 0UL
#endif

void asn1SccT_UInt32_Initialize(asn1SccT_UInt32* pVal);

#define ERR_UPER_ENCODE_T_UINT32		65  /**/
#define asn1SccT_UInt32_REQUIRED_BYTES_FOR_ENCODING       4
#define asn1SccT_UInt32_REQUIRED_BITS_FOR_ENCODING        32

flag asn1SccT_UInt32_Encode(const asn1SccT_UInt32* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints);

#define ERR_UPER_DECODE_T_UINT32		66  /**/
flag asn1SccT_UInt32_Decode(asn1SccT_UInt32* pVal, BitStream* pBitStrm, int* pErrCode);

#define asn1SccT_UInt32_REQUIRED_BYTES_FOR_ACN_ENCODING       4
#define asn1SccT_UInt32_REQUIRED_BITS_FOR_ACN_ENCODING        32

#define ERR_ACN_ENCODE_T_UINT32		67  /**/

flag asn1SccT_UInt32_ACN_Encode(const asn1SccT_UInt32* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints);

#define ERR_ACN_DECODE_T_UINT32		68  /**/
flag asn1SccT_UInt32_ACN_Decode(asn1SccT_UInt32* pVal, BitStream* pBitStrm, int* pErrCode);
/*-- asn1SccT_Runtime_Error --------------------------------------------*/

typedef enum {
    T_Runtime_Error_NONE,
    T_Runtime_Error_noerror_PRESENT,
    T_Runtime_Error_encodeerror_PRESENT,
    T_Runtime_Error_decodeerror_PRESENT
} asn1SccT_Runtime_Error_selection;

typedef union {
    asn1SccT_UInt32 noerror;
    asn1SccT_Int32 encodeerror;
    asn1SccT_Int32 decodeerror;
} asn1SccT_Runtime_Error_unchecked_union;

typedef struct {
    asn1SccT_Runtime_Error_selection kind;

    asn1SccT_Runtime_Error_unchecked_union u;
} asn1SccT_Runtime_Error;

flag asn1SccT_Runtime_Error_Equal(const asn1SccT_Runtime_Error* pVal1, const asn1SccT_Runtime_Error* pVal2);

#define ERR_T_RUNTIME_ERROR		99  /**/
#define ERR_T_RUNTIME_ERROR_NOERROR_2		74  /**/
#define ERR_T_RUNTIME_ERROR_ENCODEERROR_2		84  /**/
#define ERR_T_RUNTIME_ERROR_DECODEERROR_2		94  /**/
flag asn1SccT_Runtime_Error_IsConstraintValid(const asn1SccT_Runtime_Error* pVal, int* pErrCode);

#ifdef __cplusplus
extern const asn1SccT_Runtime_Error asn1SccT_Runtime_Error_constant;
#else
#define asn1SccT_Runtime_Error_constant {.kind = T_Runtime_Error_noerror_PRESENT, .u.noerror = 0UL}
#endif

void asn1SccT_Runtime_Error_Initialize(asn1SccT_Runtime_Error* pVal);

#define ERR_UPER_ENCODE_T_RUNTIME_ERROR		100  /**/
#define ERR_UPER_ENCODE_T_RUNTIME_ERROR_NOERROR_2		75  /**/
#define ERR_UPER_ENCODE_T_RUNTIME_ERROR_ENCODEERROR_2		85  /**/
#define ERR_UPER_ENCODE_T_RUNTIME_ERROR_DECODEERROR_2		95  /**/
#define asn1SccT_Runtime_Error_REQUIRED_BYTES_FOR_ENCODING       5
#define asn1SccT_Runtime_Error_REQUIRED_BITS_FOR_ENCODING        34

flag asn1SccT_Runtime_Error_Encode(const asn1SccT_Runtime_Error* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints);

#define ERR_UPER_DECODE_T_RUNTIME_ERROR		101  /**/
#define ERR_UPER_DECODE_T_RUNTIME_ERROR_NOERROR_2		76  /**/
#define ERR_UPER_DECODE_T_RUNTIME_ERROR_ENCODEERROR_2		86  /**/
#define ERR_UPER_DECODE_T_RUNTIME_ERROR_DECODEERROR_2		96  /**/
flag asn1SccT_Runtime_Error_Decode(asn1SccT_Runtime_Error* pVal, BitStream* pBitStrm, int* pErrCode);

#define asn1SccT_Runtime_Error_REQUIRED_BYTES_FOR_ACN_ENCODING       5
#define asn1SccT_Runtime_Error_REQUIRED_BITS_FOR_ACN_ENCODING        34

#define ERR_ACN_ENCODE_T_RUNTIME_ERROR		102  /**/
#define ERR_ACN_ENCODE_T_RUNTIME_ERROR_NOERROR_2		77  /**/
#define ERR_ACN_ENCODE_T_RUNTIME_ERROR_ENCODEERROR_2		87  /**/
#define ERR_ACN_ENCODE_T_RUNTIME_ERROR_DECODEERROR_2		97  /**/

flag asn1SccT_Runtime_Error_ACN_Encode(const asn1SccT_Runtime_Error* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints);

#define ERR_ACN_DECODE_T_RUNTIME_ERROR		103  /**/
#define ERR_ACN_DECODE_T_RUNTIME_ERROR_NOERROR_2		78  /**/
#define ERR_ACN_DECODE_T_RUNTIME_ERROR_ENCODEERROR_2		88  /**/
#define ERR_ACN_DECODE_T_RUNTIME_ERROR_DECODEERROR_2		98  /**/
flag asn1SccT_Runtime_Error_ACN_Decode(asn1SccT_Runtime_Error* pVal, BitStream* pBitStrm, int* pErrCode);
typedef asn1SccSint asn1SccT_Int8;


flag asn1SccT_Int8_Equal(const asn1SccT_Int8* pVal1, const asn1SccT_Int8* pVal2);

#define ERR_T_INT8		104  /*(-128 .. 127)*/
flag asn1SccT_Int8_IsConstraintValid(const asn1SccT_Int8* pVal, int* pErrCode);

#ifdef __cplusplus
extern const asn1SccT_Int8 asn1SccT_Int8_constant;
#else
#define asn1SccT_Int8_constant 0LL
#endif

void asn1SccT_Int8_Initialize(asn1SccT_Int8* pVal);

#define ERR_UPER_ENCODE_T_INT8		105  /**/
#define asn1SccT_Int8_REQUIRED_BYTES_FOR_ENCODING       1
#define asn1SccT_Int8_REQUIRED_BITS_FOR_ENCODING        8

flag asn1SccT_Int8_Encode(const asn1SccT_Int8* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints);

#define ERR_UPER_DECODE_T_INT8		106  /**/
flag asn1SccT_Int8_Decode(asn1SccT_Int8* pVal, BitStream* pBitStrm, int* pErrCode);

#define asn1SccT_Int8_REQUIRED_BYTES_FOR_ACN_ENCODING       1
#define asn1SccT_Int8_REQUIRED_BITS_FOR_ACN_ENCODING        8

#define ERR_ACN_ENCODE_T_INT8		107  /**/

flag asn1SccT_Int8_ACN_Encode(const asn1SccT_Int8* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints);

#define ERR_ACN_DECODE_T_INT8		108  /**/
flag asn1SccT_Int8_ACN_Decode(asn1SccT_Int8* pVal, BitStream* pBitStrm, int* pErrCode);
typedef asn1SccUint asn1SccT_UInt8;


flag asn1SccT_UInt8_Equal(const asn1SccT_UInt8* pVal1, const asn1SccT_UInt8* pVal2);

#define ERR_T_UINT8		109  /*(0 .. 255)*/
flag asn1SccT_UInt8_IsConstraintValid(const asn1SccT_UInt8* pVal, int* pErrCode);

#ifdef __cplusplus
extern const asn1SccT_UInt8 asn1SccT_UInt8_constant;
#else
#define asn1SccT_UInt8_constant 0UL
#endif

void asn1SccT_UInt8_Initialize(asn1SccT_UInt8* pVal);

#define ERR_UPER_ENCODE_T_UINT8		110  /**/
#define asn1SccT_UInt8_REQUIRED_BYTES_FOR_ENCODING       1
#define asn1SccT_UInt8_REQUIRED_BITS_FOR_ENCODING        8

flag asn1SccT_UInt8_Encode(const asn1SccT_UInt8* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints);

#define ERR_UPER_DECODE_T_UINT8		111  /**/
flag asn1SccT_UInt8_Decode(asn1SccT_UInt8* pVal, BitStream* pBitStrm, int* pErrCode);

#define asn1SccT_UInt8_REQUIRED_BYTES_FOR_ACN_ENCODING       1
#define asn1SccT_UInt8_REQUIRED_BITS_FOR_ACN_ENCODING        8

#define ERR_ACN_ENCODE_T_UINT8		112  /**/

flag asn1SccT_UInt8_ACN_Encode(const asn1SccT_UInt8* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints);

#define ERR_ACN_DECODE_T_UINT8		113  /**/
flag asn1SccT_UInt8_ACN_Decode(asn1SccT_UInt8* pVal, BitStream* pBitStrm, int* pErrCode);
typedef flag asn1SccT_Boolean;


flag asn1SccT_Boolean_Equal(const asn1SccT_Boolean* pVal1, const asn1SccT_Boolean* pVal2);

#define ERR_T_BOOLEAN		114  /**/
flag asn1SccT_Boolean_IsConstraintValid(const asn1SccT_Boolean* pVal, int* pErrCode);

#ifdef __cplusplus
extern const asn1SccT_Boolean asn1SccT_Boolean_constant;
#else
#define asn1SccT_Boolean_constant FALSE
#endif

void asn1SccT_Boolean_Initialize(asn1SccT_Boolean* pVal);

#define ERR_UPER_ENCODE_T_BOOLEAN		115  /**/
#define asn1SccT_Boolean_REQUIRED_BYTES_FOR_ENCODING       1
#define asn1SccT_Boolean_REQUIRED_BITS_FOR_ENCODING        1

flag asn1SccT_Boolean_Encode(const asn1SccT_Boolean* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints);

#define ERR_UPER_DECODE_T_BOOLEAN		116  /**/
flag asn1SccT_Boolean_Decode(asn1SccT_Boolean* pVal, BitStream* pBitStrm, int* pErrCode);

#define asn1SccT_Boolean_REQUIRED_BYTES_FOR_ACN_ENCODING       1
#define asn1SccT_Boolean_REQUIRED_BITS_FOR_ACN_ENCODING        1

#define ERR_ACN_ENCODE_T_BOOLEAN		117  /**/

flag asn1SccT_Boolean_ACN_Encode(const asn1SccT_Boolean* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints);

#define ERR_ACN_DECODE_T_BOOLEAN		118  /**/
flag asn1SccT_Boolean_ACN_Decode(asn1SccT_Boolean* pVal, BitStream* pBitStrm, int* pErrCode);
/*-- asn1SccT_Null_Record --------------------------------------------*/
typedef struct {

} asn1SccT_Null_Record;

flag asn1SccT_Null_Record_Equal(const asn1SccT_Null_Record* pVal1, const asn1SccT_Null_Record* pVal2);

#define ERR_T_NULL_RECORD		119  /**/
flag asn1SccT_Null_Record_IsConstraintValid(const asn1SccT_Null_Record* pVal, int* pErrCode);

#ifdef __cplusplus
extern const asn1SccT_Null_Record asn1SccT_Null_Record_constant;
#else
#define asn1SccT_Null_Record_constant {}
#endif

void asn1SccT_Null_Record_Initialize(asn1SccT_Null_Record* pVal);

#define asn1SccT_Null_Record_REQUIRED_BYTES_FOR_ENCODING       0
#define asn1SccT_Null_Record_REQUIRED_BITS_FOR_ENCODING        0

flag asn1SccT_Null_Record_Encode(const asn1SccT_Null_Record* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints);

flag asn1SccT_Null_Record_Decode(asn1SccT_Null_Record* pVal, BitStream* pBitStrm, int* pErrCode);

#define asn1SccT_Null_Record_REQUIRED_BYTES_FOR_ACN_ENCODING       0
#define asn1SccT_Null_Record_REQUIRED_BITS_FOR_ACN_ENCODING        0


flag asn1SccT_Null_Record_ACN_Encode(const asn1SccT_Null_Record* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints);

flag asn1SccT_Null_Record_ACN_Decode(asn1SccT_Null_Record* pVal, BitStream* pBitStrm, int* pErrCode);
typedef asn1SccUint asn1SccPID_Range;


flag asn1SccPID_Range_Equal(const asn1SccPID_Range* pVal1, const asn1SccPID_Range* pVal2);

#define ERR_PID_RANGE		124  /*(0..5)*/
flag asn1SccPID_Range_IsConstraintValid(const asn1SccPID_Range* pVal, int* pErrCode);

#ifdef __cplusplus
extern const asn1SccPID_Range asn1SccPID_Range_constant;
#else
#define asn1SccPID_Range_constant 0UL
#endif

void asn1SccPID_Range_Initialize(asn1SccPID_Range* pVal);

#define ERR_UPER_ENCODE_PID_RANGE		125  /**/
#define asn1SccPID_Range_REQUIRED_BYTES_FOR_ENCODING       1
#define asn1SccPID_Range_REQUIRED_BITS_FOR_ENCODING        3

flag asn1SccPID_Range_Encode(const asn1SccPID_Range* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints);

#define ERR_UPER_DECODE_PID_RANGE		126  /**/
flag asn1SccPID_Range_Decode(asn1SccPID_Range* pVal, BitStream* pBitStrm, int* pErrCode);

#define asn1SccPID_Range_REQUIRED_BYTES_FOR_ACN_ENCODING       1
#define asn1SccPID_Range_REQUIRED_BITS_FOR_ACN_ENCODING        3

#define ERR_ACN_ENCODE_PID_RANGE		127  /**/

flag asn1SccPID_Range_ACN_Encode(const asn1SccPID_Range* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints);

#define ERR_ACN_DECODE_PID_RANGE		128  /**/
flag asn1SccPID_Range_ACN_Decode(asn1SccPID_Range* pVal, BitStream* pBitStrm, int* pErrCode);
typedef enum {
    PID_controller = 0,
    PID_datapool = 1,
    PID_manager = 2,
    PID_utilities = 3,
    PID_samv71asw_timer_manager = 4,
    PID_env = 5
} asn1SccPID;

// please use the following macros to avoid breaking code.
#define asn1SccPID_controller PID_controller
#define asn1SccPID_datapool PID_datapool
#define asn1SccPID_manager PID_manager
#define asn1SccPID_utilities PID_utilities
#define asn1SccPID_samv71asw_timer_manager PID_samv71asw_timer_manager
#define asn1SccPID_env PID_env

flag asn1SccPID_Equal(const asn1SccPID* pVal1, const asn1SccPID* pVal2);

#define ERR_PID		129  /*controller | datapool | manager | utilities | samv71asw-timer-manager | env*/
flag asn1SccPID_IsConstraintValid(const asn1SccPID* pVal, int* pErrCode);

#ifdef __cplusplus
extern const asn1SccPID asn1SccPID_constant;
#else
#define asn1SccPID_constant PID_controller
#endif

void asn1SccPID_Initialize(asn1SccPID* pVal);

#define ERR_UPER_ENCODE_PID		130  /**/
#define asn1SccPID_REQUIRED_BYTES_FOR_ENCODING       1
#define asn1SccPID_REQUIRED_BITS_FOR_ENCODING        3

flag asn1SccPID_Encode(const asn1SccPID* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints);

#define ERR_UPER_DECODE_PID		131  /**/
flag asn1SccPID_Decode(asn1SccPID* pVal, BitStream* pBitStrm, int* pErrCode);

#define asn1SccPID_REQUIRED_BYTES_FOR_ACN_ENCODING       1
#define asn1SccPID_REQUIRED_BITS_FOR_ACN_ENCODING        3

#define ERR_ACN_ENCODE_PID		132  /**/

flag asn1SccPID_ACN_Encode(const asn1SccPID* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints);

#define ERR_ACN_DECODE_PID		133  /**/
flag asn1SccPID_ACN_Decode(asn1SccPID* pVal, BitStream* pBitStrm, int* pErrCode);


/* ================= Encoding/Decoding function prototypes =================
 * These functions are placed at the end of the file to make sure all types
 * have been declared first, in case of parameterized ACN encodings
 * ========================================================================= */



#ifdef  __cplusplus
}

#endif

#endif
