#ifndef GENERATED_ASN1SCC_manager_datamodel_H
#define GENERATED_ASN1SCC_manager_datamodel_H
/*
Code automatically generated by asn1scc tool
*/
#include "asn1crt.h"
#include "dataview-uniq.h"

#ifdef  __cplusplus
extern "C" {
#endif


typedef enum {
    asn1Sccwait = 0
} asn1SccManager_States;

// please use the following macros to avoid breaking code.
#define asn1SccManager_States_wait asn1Sccwait

flag asn1SccManager_States_Equal(const asn1SccManager_States* pVal1, const asn1SccManager_States* pVal2);

#define ERR_MANAGER_STATES		1  /*wait*/
flag asn1SccManager_States_IsConstraintValid(const asn1SccManager_States* pVal, int* pErrCode);

#ifdef __cplusplus
extern const asn1SccManager_States asn1SccManager_States_constant;
#else
#define asn1SccManager_States_constant asn1Sccwait
#endif

void asn1SccManager_States_Initialize(asn1SccManager_States* pVal);
/*-- asn1SccManager_Context --------------------------------------------*/
typedef struct {
    asn1SccManager_States state;
    flag init_done;
    asn1SccPID sender;
    asn1SccPID offspring;

} asn1SccManager_Context;

flag asn1SccManager_Context_Equal(const asn1SccManager_Context* pVal1, const asn1SccManager_Context* pVal2);

#define ERR_MANAGER_CONTEXT		181  /**/
#define ERR_MANAGER_CONTEXT_STATE_2		151  /**/
#define ERR_MANAGER_CONTEXT_INIT_DONE		156  /**/
#define ERR_MANAGER_CONTEXT_SENDER_2		166  /**/
#define ERR_MANAGER_CONTEXT_OFFSPRING_2		176  /**/
flag asn1SccManager_Context_IsConstraintValid(const asn1SccManager_Context* pVal, int* pErrCode);

#ifdef __cplusplus
extern const asn1SccManager_Context asn1SccManager_Context_constant;
#else
#define asn1SccManager_Context_constant {.state = asn1Sccwait, .init_done = FALSE, .sender = asn1Scccontroller, .offspring = asn1Scccontroller}
#endif

void asn1SccManager_Context_Initialize(asn1SccManager_Context* pVal);
typedef enum {
    asn1SccparamU8_present = 1,
    asn1SccparamF_present = 2
} asn1SccManager_Parametervalue_Val_Selection;

// please use the following macros to avoid breaking code.
#define asn1SccManager_Parametervalue_Val_Selection_paramU8_present asn1SccparamU8_present
#define asn1SccManager_Parametervalue_Val_Selection_paramF_present asn1SccparamF_present

flag asn1SccManager_Parametervalue_Val_Selection_Equal(const asn1SccManager_Parametervalue_Val_Selection* pVal1, const asn1SccManager_Parametervalue_Val_Selection* pVal2);

#define ERR_MANAGER_PARAMETERVALUE_VAL_SELECTION		6  /*paramU8-present | paramF-present*/
flag asn1SccManager_Parametervalue_Val_Selection_IsConstraintValid(const asn1SccManager_Parametervalue_Val_Selection* pVal, int* pErrCode);

#ifdef __cplusplus
extern const asn1SccManager_Parametervalue_Val_Selection asn1SccManager_Parametervalue_Val_Selection_constant;
#else
#define asn1SccManager_Parametervalue_Val_Selection_constant asn1SccparamU8_present
#endif

void asn1SccManager_Parametervalue_Val_Selection_Initialize(asn1SccManager_Parametervalue_Val_Selection* pVal);
typedef enum {
    asn1Sccnoerror_present = 1,
    asn1Sccencodeerror_present = 2,
    asn1Sccdecodeerror_present = 3
} asn1SccManager_T_Runtime_Error_Selection;

// please use the following macros to avoid breaking code.
#define asn1SccManager_T_Runtime_Error_Selection_noerror_present asn1Sccnoerror_present
#define asn1SccManager_T_Runtime_Error_Selection_encodeerror_present asn1Sccencodeerror_present
#define asn1SccManager_T_Runtime_Error_Selection_decodeerror_present asn1Sccdecodeerror_present

flag asn1SccManager_T_Runtime_Error_Selection_Equal(const asn1SccManager_T_Runtime_Error_Selection* pVal1, const asn1SccManager_T_Runtime_Error_Selection* pVal2);

#define ERR_MANAGER_T_RUNTIME_ERROR_SELECTION		11  /*noerror-present | encodeerror-present | decodeerror-present*/
flag asn1SccManager_T_Runtime_Error_Selection_IsConstraintValid(const asn1SccManager_T_Runtime_Error_Selection* pVal, int* pErrCode);

#ifdef __cplusplus
extern const asn1SccManager_T_Runtime_Error_Selection asn1SccManager_T_Runtime_Error_Selection_constant;
#else
#define asn1SccManager_T_Runtime_Error_Selection_constant asn1Sccnoerror_present
#endif

void asn1SccManager_T_Runtime_Error_Selection_Initialize(asn1SccManager_T_Runtime_Error_Selection* pVal);


/* ================= Encoding/Decoding function prototypes =================
 * These functions are placed at the end of the file to make sure all types
 * have been declared first, in case of parameterized ACN encodings
 * ========================================================================= */



#ifdef  __cplusplus
}

#endif

#endif
