#ifndef __PRINTTYPESASASN1_H__
#define __PRINTTYPESASASN1_H__

#ifdef __cplusplus
extern "C" {
#endif

#include "dataview-uniq.h" // Generated by ASN1SCC

void PrintASN1UInt8T(const char *paramName, const asn1SccUInt8T *pData);
void PrintASN1UInt16T(const char *paramName, const asn1SccUInt16T *pData);
void PrintASN1Float32(const char *paramName, const asn1SccFloat32 *pData);
void PrintASN1ParameterValue(const char *paramName, const asn1SccParameterValue *pData);
void PrintASN1Flag8(const char *paramName, const asn1SccFlag8 *pData);
void PrintASN1ParameterID(const char *paramName, const asn1SccParameterID *pData);
void PrintASN1T_Int32(const char *paramName, const asn1SccT_Int32 *pData);
void PrintASN1T_UInt32(const char *paramName, const asn1SccT_UInt32 *pData);
void PrintASN1T_Runtime_Error(const char *paramName, const asn1SccT_Runtime_Error *pData);
void PrintASN1T_Int8(const char *paramName, const asn1SccT_Int8 *pData);
void PrintASN1T_UInt8(const char *paramName, const asn1SccT_UInt8 *pData);
void PrintASN1T_Boolean(const char *paramName, const asn1SccT_Boolean *pData);
void PrintASN1T_Null_Record(const char *paramName, const asn1SccT_Null_Record *pData);
void PrintASN1PID_Range(const char *paramName, const asn1SccPID_Range *pData);
void PrintASN1PID(const char *paramName, const asn1SccPID *pData);

#ifdef __cplusplus
}
#endif

#endif
