// Autogenerated code (from TASTE/Kazoo) : DO NOT EDIT

#include "demo_timer_manager.h"

// When manager_cooldowntimer expires, this function is called:
extern void demo_timer_manager_RI_manager_cooldowntimer(void);

void demo_timer_manager_startup(void)
{
 // Timer start up (nothing to do)
}

void demo_timer_manager_PI_Tick(void)
{
   if (active == timers[manager_cooldowntimer].state && 0 == -- timers[manager_cooldowntimer].value) {
      demo_timer_manager_RI_manager_cooldowntimer();
      timers[manager_cooldowntimer].state = inactive;
   }

}

void demo_timer_manager_PI_SET_manager_cooldowntimer(asn1SccT_UInt32 *val)
{
   /* Timer value must be multiple of 10 ms */
   assert (0 == (*val % 10));
   timers[manager_cooldowntimer].state = active;
   timers[manager_cooldowntimer].value = *val / 10;
}

void demo_timer_manager_PI_RESET_manager_cooldowntimer(void)
{
   timers[manager_cooldowntimer].state = inactive;
}


