/* Body file for function demo_Timer_Manager
 * Generated by TASTE (kazoo/templates/glue/language_wrappers/vm-if-body/function.tmplt)
 */
#include "demo_timer_manager_vm_if.h"
#include "routing.h"

// Define a global PID variable used to keep track of the sender of the last message
static asn1SccPID sender_pid = PID_env;

// API to provide to the user code the PID of the last PI caller
void demo_timer_manager_get_sender(asn1SccPID *OUT_sender_pid, asn1SccPID unused)
{
  *OUT_sender_pid = sender_pid;
}




unsigned demo_timer_manager_initialized = 0;
void init_demo_timer_manager(void)
{
   if (0 == demo_timer_manager_initialized) {
      // Initialize epoch for the MSC tracing in debug mode
      long long unused __attribute__((unused)) = getTimeInMilliseconds();
      demo_timer_manager_initialized = 1;
      // Call user code startup function
      extern void demo_timer_manager_startup(void);
      demo_timer_manager_startup();
      puts ("[TASTE] Initialization completed for function demo_Timer_Manager");
      demo_timer_manager_initialized = 2;
   }
}
void demo_timer_manager_RESET_manager_cooldowntimer(void)
{
   sender_pid = demo_timer_manager_reset_manager_cooldowntimer_get_sender();
   // In Debug mode and x86 builts only: log MSC data when environment variable is set
   static int innerMsc = -1;
   if (-1 == innerMsc)
     innerMsc = (NULL != getenv("TASTE_INNER_MSC"))?1:0;
   if (1 == innerMsc) {
      long long msc_time = getTimeInMilliseconds();
      printf ("INNER_PI: demo_timer_manager,reset_manager_cooldowntimer,%lld\n", msc_time);
      fflush(stdout);
   }

   //  Directly call user code, no parameters to pass
   extern void demo_timer_manager_PI_RESET_manager_cooldowntimer(void);
   demo_timer_manager_PI_RESET_manager_cooldowntimer();
   // puts ("demo_timer_manager_reset_manager_cooldowntimer called");
}




void demo_timer_manager_SET_manager_cooldowntimer
      (const char *IN_val, size_t IN_val_len)

{
   sender_pid = demo_timer_manager_set_manager_cooldowntimer_get_sender();
   // In Debug mode and x86 builts only: log MSC data when environment variable is set
   static int innerMsc = -1;
   if (-1 == innerMsc)
     innerMsc = (NULL != getenv("TASTE_INNER_MSC"))?1:0;
   if (1 == innerMsc) {
      long long msc_time = getTimeInMilliseconds();
      printf ("INNER_PI: demo_timer_manager,set_manager_cooldowntimer,%lld\n", msc_time);
      fflush(stdout);
   }

   //  Declare user code function as external (it may not have a .h if it is in Ada)
   extern void demo_timer_manager_PI_SET_manager_cooldowntimer
      (const asn1SccT_UInt32 *);





   // Call user code
   demo_timer_manager_PI_SET_manager_cooldowntimer ((asn1SccT_UInt32 *)IN_val);

}




void demo_timer_manager_Tick(void)
{
   // In Debug mode and x86 builts only: log MSC data when environment variable is set
   static int innerMsc = -1;
   if (-1 == innerMsc)
     innerMsc = (NULL != getenv("TASTE_INNER_MSC"))?1:0;
   if (1 == innerMsc) {
      long long msc_time = getTimeInMilliseconds();
      printf ("INNER_PI: demo_timer_manager,tick,%lld\n", msc_time);
      fflush(stdout);
   }

   //  Directly call user code, no parameters to pass
   extern void demo_timer_manager_PI_Tick(void);
   demo_timer_manager_PI_Tick();
   // puts ("demo_timer_manager_tick called");
}

