/* Body file for function Controller
 * Generated by TASTE (kazoo/templates/skeletons/c-body/function.tmplt)
 * You can edit this file, it will not be overwritten

    !! IMPORTANT                                                        !!
    !! When you modify your design (interface view), you must update    !!
    !! the procedures corresponding to the provided interfaces in this  !!
    !! file. The up-to-date signatures can be found in the header file. !!
*/
#include "controller.h"
//#include <stdio.h>


void controller_startup(void)
{
   // Write your initialisation code
   // You may call sporadic required interfaces and start timers
   // puts ("[Controller] Startup");
}

void controller_PI_activate(void)
{
   // Write your code here
}


void controller_PI_deactivate(void)
{
   // Write your code here
}


void controller_PI_pps(void)
{
   // Write your code here
}


