/* Header file for function Controller
 * Generated by TASTE (kazoo/templates/skeletons/c-header/function.tmplt)
 * DO NOT EDIT THIS FILE, IT WILL BE OVERWRITTEN DURING THE BUILD
 */

#pragma once

#include "dataview-uniq.h"

#ifdef __cplusplus
extern "C" {
#endif


void controller_startup(void);

/* Provided interfaces */
void controller_PI_activate( void );


void controller_PI_deactivate( void );


void controller_PI_pps( void );

/* Required interfaces */
extern void controller_RI_fib( const asn1SccT_UInt32 *, asn1SccT_UInt32 * );


extern void controller_RI_mulf( const asn1SccFloat32 *, const asn1SccFloat32 *, asn1SccFloat32 * );


extern void controller_RI_read_param( const asn1SccParameterID *, asn1SccParameterValue *, asn1SccFlag8 * );


extern void controller_RI_report_oor( void );


extern void controller_RI_write_param( const asn1SccParameterValue *, asn1SccFlag8 * );


#ifdef __cplusplus
}
#endif
