/* Body file for function Utilities
 * Generated by TASTE (kazoo/templates/skeletons/c-body/function.tmplt)
 * You can edit this file, it will not be overwritten

    !! IMPORTANT                                                        !!
    !! When you modify your design (interface view), you must update    !!
    !! the procedures corresponding to the provided interfaces in this  !!
    !! file. The up-to-date signatures can be found in the header file. !!
*/
#include "utilities.h"
//#include <stdio.h>


void utilities_startup(void)
{

}

void utilities_PI_fib
      (const asn1SccT_UInt32 *IN_p,
       asn1SccT_UInt32 *OUT_r)

{
    switch (*IN_p)
    {
    case 0:
        *OUT_r = 0;
        return;
    case 1:
        *OUT_r = 1;
        return;
    default:
        {
            uint32_t x1 = 0;
            uint32_t x2 = 1;
            uint32_t r;
            for (uint32_t i = 2; i <= *IN_p; i++)
            {
                r = x1 + x2;
                x1 = x2;
                x2 = r;
            }
            *OUT_r = r;
        }
    }
}


void utilities_PI_mulf
      (const asn1SccFloat32 *IN_a,
       const asn1SccFloat32 *IN_b,
       asn1SccFloat32 *OUT_r)

{
    *OUT_r = *IN_a * *IN_b;
}


