/* Body file for function Utilities
 * Generated by TASTE (kazoo/templates/skeletons/c-body/function.tmplt)
 * You can edit this file, it will not be overwritten

    !! IMPORTANT                                                        !!
    !! When you modify your design (interface view), you must update    !!
    !! the procedures corresponding to the provided interfaces in this  !!
    !! file. The up-to-date signatures can be found in the header file. !!
*/
#include "utilities.h"

/**
 * @file Utilities
 * 
 */


void utilities_startup(void)
{

}

/**
 * @brief Calculates the nth Fibonacci number
 * @param IN_p Pointer to input parameter (n-th position in Fibonacci sequence)
 * @param OUT_r Pointer to output parameter (result of Fibonacci calculation)
 * @return void
 * 
 * @satisfies DEMO-FUN-UTILS-001
 * 
 * Computes the Fibonacci number at position n using an iterative approach.
 * Base cases: fib(0) = 0, fib(1) = 1
 */
void utilities_PI_fib
      (const asn1SccT_UInt32 *IN_p,
       asn1SccT_UInt32 *OUT_r)

{
    switch (*IN_p)
    {
    case 0:
        *OUT_r = 0;
        return;
    case 1:
        *OUT_r = 1;
        return;
    default:
        {
            uint32_t x1 = 0;
            uint32_t x2 = 1;
            uint32_t r;
            for (uint32_t i = 2; i <= *IN_p; i++)
            {
                r = x1 + x2;
                x1 = x2;
                x2 = r;
            }
            *OUT_r = r;
        }
    }
}



/**
 * @brief Multiplies two floating-point numbers
 * @param IN_a Pointer to first input parameter (multiplicand)
 * @param IN_b Pointer to second input parameter (multiplier)
 * @param OUT_r Pointer to output parameter (result of multiplication)
 * @return void
 * 
 * @satisfies DEMO-FUN-UTILS-002
 * 
 * Performs multiplication of two 32-bit floating-point values.
 */
void utilities_PI_mulf
      (const asn1SccFloat32 *IN_a,
       const asn1SccFloat32 *IN_b,
       asn1SccFloat32 *OUT_r)

{
    *OUT_r = *IN_a * *IN_b;
}


