/* Header file for function Utilities
 * Generated by TASTE (kazoo/templates/skeletons/c-header/function.tmplt)
 * DO NOT EDIT THIS FILE, IT WILL BE OVERWRITTEN DURING THE BUILD
 */

#pragma once

#include "dataview-uniq.h"

#ifdef __cplusplus
extern "C" {
#endif

#include <stdlib.h>
#include <stdio.h>

void utilities_startup(void);

/* Provided interfaces */
void utilities_PI_fib( const asn1SccT_UInt32 *, asn1SccT_UInt32 * );


void utilities_PI_mulf( const asn1SccFloat32 *, const asn1SccFloat32 *, asn1SccFloat32 * );

/* Required interfaces */



#ifdef __cplusplus
}
#endif
