# MAKEFILE_PATH   := $(abspath $(lastword $(MAKEFILE_LIST)))
MAKEFILE_PATH   := $(lastword $(MAKEFILE_LIST))
TOOL_INST       := $(shell taste-config --prefix)
OUTDIR          := $(dir $(MAKEFILE_PATH))
TASTE_SHARED_TYPES?=${HOME}/.local/share/QtProject/QtCreator/shared_types
ASN1_FILES      :=../demo-taste-project.asn ${TOOL_INST}/share/taste-types/taste-types.asn system.asn
CP_FILES        :=       # Context parameters
DATAVIEW_PATH   := ${OUTDIR}/dataview
DATAVIEW_UNIQ   := ${DATAVIEW_PATH}/dataview-uniq.asn
DATAVIEW_ACN    := ${DATAVIEW_PATH}/dataview-uniq.acn
# the dataview with AADLv1 data is generated in Python by asn2aadlPlus
DATAVIEW_AADLV1 := ${DATAVIEW_PATH}/dataview_aadlv1.aadl
ASN1_POLICY_FLAGS ?= -typePrefix asn1Scc -renamePolicy 3 -equal -fp AUTO -c -ig -uPER -ACN
#TASTE_SHARED_TYPES?=${TOOL_INST}/share/SharedTypes  # Ellidiss only

# These languages are used in the system: C, Timer_Manager
# Project cache folder is used to speed up all ASN.1-related processing
export PROJECT_CACHE=${HOME}/.taste_AST_cache
export IV_FILE=$(shell readlink -f ../interfaceview.xml)
all:	build-default
	$(info Run "make -C work check_stack" to analyze the stack usage of your application")

# Call the stack checker
check_stack:
	$(MAKE) -C build -f Makefile.taste check_stack


# Check that all runtimes used in the system are installed
check_targets:
	$(MAKE) -C build -f Makefile.taste check_targets

# Generate the language-specific data view needed before editing user code
dataview:	${DATAVIEW_UNIQ} dataview/C/built
	# Copy the dataview to SDL/SEDS function Manager (no context parameters)
	cp -u ${DATAVIEW_UNIQ} manager/SDL/src
	# Compute MD5 of the dataview, needed to decide if code needs to be re-generated
	md5sum -c "manager/SDL/src/dataview.md5" > /dev/null 2>&1 || md5sum  "manager/SDL/src/dataview-uniq.asn" >  "manager/SDL/src/dataview.md5"
	# Pre-cache the Dataview for opengeode to speed up parsing
	taste-cache-datamodel-for-sdl --toC

# Generate the complete dataview, including Python bindings if there is a GUI
${DATAVIEW_PATH}/built:  dataview/C/built dataview
	touch $@

${DATAVIEW_AADLV1}: ${DATAVIEW_UNIQ}
	echo [-] Generate dataview entry in Python for aadl2glueC
	asn2aadlPlus  $< $@


# Build based on the deployment view
# The parallel invocation can not be added here because of matlab remote error
# For local matlab instalation it can be added
build-default:	aadl2glueC build/system_config.h ${DATAVIEW_PATH}/built build/deploymentview_final/Makefile
	$(MAKE) -C build -f Makefile.taste

# Execute the generated binaries (used in Space Creator when using the Run button)
run: # Space creator will always build before, so no need to depend on build-default
	$(MAKE) -j -C build -f Makefile.taste run

# Run the Concurrency View analysis tool (cheddar/marzhin)
run_cv: build/ConcurrencyView.aadl
	TASTECV --load $^

# The Concurrency View needed by Cheddar is the concatenation of system.aadl and ocarina_components.aadl
build/ConcurrencyView.aadl:	build/system.aadl
	cat $^ $(shell taste-config --prefix)/share/ocarina/AADLv2/ocarina_components.aadl > $@

# Rule to invoke Ocarina (generation of POHI middleware code)
build/deploymentview_final/Makefile:	build/main.aadl ${DATAVIEW_UNIQ}
	# Nothing will be generated if POHIC is not needed
	$(MAKE) -C build -f Makefile.taste ocarina

# Optionally manage SQL Database (run taste-create-database to enable)
sql_db/DV.py:
	mkdir -p sql_db && touch $@

# Create dataview-uniq.asn by concatenating all asn1 input files
${DATAVIEW_UNIQ}:	${ASN1_FILES}
	mkdir -p ${PROJECT_CACHE} && mkdir -p ${DATAVIEW_PATH}
	sed -e '$$s/$$/\n/' -s $^ > $@

# Create dataview-uniq.acn by concatenating all input files
${DATAVIEW_ACN}:	../demo-taste-project.acn
	mkdir -p ${DATAVIEW_PATH}
	sed -e '$$s/$$/\n/' -s $^ > $@

# system_config.h is used to filter out non-needed ASN.1 encoder/decoders
build/system_config.h:	$(wildcard */*/wrappers/*_system_config.h)
	cat $^ > $@

#  Call DMT/aadl2glueC to generate glue code from the mini-cv.aadl files
aadl2glueC:	controller/C/wrappers/aadl2glueC_built datapool/C/wrappers/aadl2glueC_built demo_timer_manager/Timer_Manager/wrappers/aadl2glueC_built manager/SDL/wrappers/aadl2glueC_built utilities/C/wrappers/aadl2glueC_built

controller/C/wrappers/aadl2glueC_built: controller/C/wrappers/controller_mini_cv.aadl ${DATAVIEW_AADLV1}
	touch $@

datapool/C/wrappers/aadl2glueC_built: datapool/C/wrappers/datapool_mini_cv.aadl ${DATAVIEW_AADLV1}
	touch $@

demo_timer_manager/Timer_Manager/wrappers/aadl2glueC_built: demo_timer_manager/Timer_Manager/wrappers/demo_timer_manager_mini_cv.aadl ${DATAVIEW_AADLV1}
	aadl2glueC -allboards -o $(dir $@) $^
	touch $@

manager/SDL/wrappers/aadl2glueC_built: manager/SDL/wrappers/manager_mini_cv.aadl ${DATAVIEW_AADLV1}
	touch $@

utilities/C/wrappers/aadl2glueC_built: utilities/C/wrappers/utilities_mini_cv.aadl ${DATAVIEW_AADLV1}
	touch $@


# Compile the ASN.1 models in C
dataview/C/built: ${DATAVIEW_UNIQ} ${DATAVIEW_ACN} ${CP_FILES}
	$(info [-] Compiling the dataview in C)
	mkdir -p $(dir $@)
	asn1scc ${ASN1SCC_FLAGS} -o $(dir $@) ${ASN1_POLICY_FLAGS} $^
	cp ${TOOL_INST}/share/AutoGUI/debug_messages.? dataview/C
	cp ${TOOL_INST}/share/AutoGUI/timeInMS.? dataview/C
	cd dataview/C && msgPrinterASN1 ../dataview-uniq.asn
	touch $@



simulink_skeletons:
	# target required only for SIMULINK and VHDL, which use specific DMT paths
	# empty otherwise

clean:
	rm -rf binaries dataview
	$(MAKE) -C build -f Makefile.taste clean

.PHONY: clean simu compile-all-linux function-instances-linux function-types-linux build-default dataview build-rtems-ada dataview build/modelchecking modelchecking/subtypes/$(SUBTYPE) obs-to-if aadl-to-if asn-to-if $(PROPERTIES_CONFIG) run_cv simulink_skeletons

