/* Body file for function Utilities
 * Generated by TASTE (kazoo/templates/glue/language_wrappers/vm-if-body/function.tmplt)
 */
#include "utilities_vm_if.h"
#include "routing.h"

// Define a global PID variable used to keep track of the sender of the last message
static asn1SccPID sender_pid = PID_env;

// API to provide to the user code the PID of the last PI caller
void utilities_get_sender(asn1SccPID *OUT_sender_pid, asn1SccPID unused)
{
  *OUT_sender_pid = sender_pid;
}



extern void adainit(void);

unsigned utilities_initialized = 0;
void init_utilities(void)
{
   if (0 == utilities_initialized) {
      // Initialize epoch for the MSC tracing in debug mode
      long long unused __attribute__((unused)) = getTimeInMilliseconds();
      utilities_initialized = 1;
      // Call user code startup function
      extern void utilities_startup(void);
      utilities_startup();
      puts ("[TASTE] Initialization completed for function Utilities");
      utilities_initialized = 2;
   }
}
void utilities_fib
      (const char *IN_p, size_t IN_p_len,
       char *OUT_r, size_t *OUT_r_len)

{
   sender_pid = utilities_fib_get_sender();
   // In Debug mode and x86 builts only: log MSC data when environment variable is set
   static int innerMsc = -1;
   if (-1 == innerMsc)
     innerMsc = (NULL != getenv("TASTE_INNER_MSC"))?1:0;
   if (1 == innerMsc) {
      long long msc_time = getTimeInMilliseconds();
      printf ("INNER_PI: utilities,fib,%lld\n", msc_time);
      fflush(stdout);
   }

   //  Declare user code function as external (it may not have a .h if it is in Ada)
   extern void utilities_PI_fib
      (const asn1SccT_UInt32 *,
       asn1SccT_UInt32 *);





   // Call user code
   utilities_PI_fib ((asn1SccT_UInt32 *)IN_p, (asn1SccT_UInt32 *)OUT_r);

}




void utilities_mulf
      (const char *IN_a, size_t IN_a_len,
       const char *IN_b, size_t IN_b_len,
       char *OUT_r, size_t *OUT_r_len)

{
   sender_pid = utilities_mulf_get_sender();
   // In Debug mode and x86 builts only: log MSC data when environment variable is set
   static int innerMsc = -1;
   if (-1 == innerMsc)
     innerMsc = (NULL != getenv("TASTE_INNER_MSC"))?1:0;
   if (1 == innerMsc) {
      long long msc_time = getTimeInMilliseconds();
      printf ("INNER_PI: utilities,mulf,%lld\n", msc_time);
      fflush(stdout);
   }

   //  Declare user code function as external (it may not have a .h if it is in Ada)
   extern void utilities_PI_mulf
      (const asn1SccFloat32 *,
       const asn1SccFloat32 *,
       asn1SccFloat32 *);





   // Call user code
   utilities_PI_mulf ((asn1SccFloat32 *)IN_a, (asn1SccFloat32 *)IN_b, (asn1SccFloat32 *)OUT_r);

}

