/* ASN.1 System configuration file for function Utilities
 * Generated by TASTE (kazoo/templates/glue/language_wrappers/system_config/function.tmplt)
 */
#define __NEED_T_UInt32_NATIVE
#define __NEED_T_UInt32_NATIVE


#define __NEED_Float32_NATIVE
#define __NEED_Float32_NATIVE
#define __NEED_Float32_NATIVE

