/* Header file for function Utilities
 * Generated by TASTE (kazoo/templates/glue/language_wrappers/vm_if-header/function.tmplt)
 * DO NOT EDIT THIS FILE, IT WILL BE OVERWRITTEN DURING THE BUILD
 */

/* The purpose of this file is to provide a wrapper around the user code,
 * with a single interface that is independent of the implementation language
 * of the function. The parameters of each PI are blackboxes encoded
 * in the form specified in the interface view (Native, uPER, or ACN)
*/

#pragma once
#if defined(__unix__) || defined (__MSP430__)
   #include <stdlib.h>
   #include <stdio.h>
#else
   typedef unsigned size_t;
#endif

#include "C_ASN1_Types.h"
#include <stdio.h>
extern long long getTimeInMilliseconds(void);
#ifdef __cplusplus
extern "C" {
#endif

#include "utilities.h"

// Function initialization - calls user startup code of all dependent functions
void init_utilities(void);


/* Provided interfaces */
void utilities_fib
      (const char *IN_p, size_t IN_p_len,
       char *OUT_r, size_t *OUT_r_len);



void utilities_mulf
      (const char *IN_a, size_t IN_a_len,
       const char *IN_b, size_t IN_b_len,
       char *OUT_r, size_t *OUT_r_len);


#ifdef __cplusplus
}
#endif

