/* Header file for function DataPool
 * Generated by TASTE (kazoo/templates/skeletons/c-header/function.tmplt)
 * DO NOT EDIT THIS FILE, IT WILL BE OVERWRITTEN DURING THE BUILD
 */

#pragma once

#include "dataview-uniq.h"

#ifdef __cplusplus
extern "C" {
#endif

#include <stdlib.h>
#include <stdio.h>

void datapool_startup(void);

/* Provided interfaces */
void datapool_PI_read_param( const asn1SccParameterID *, asn1SccParameterValue *, asn1SccFlag8 * );


void datapool_PI_write_param( const asn1SccParameterValue *, asn1SccFlag8 * );

/* Required interfaces */



#ifdef __cplusplus
}
#endif
