/* Body file for function DataPool
 * Generated by TASTE (kazoo/templates/skeletons/c-body/function.tmplt)
 * You can edit this file, it will not be overwritten

    !! IMPORTANT                                                        !!
    !! When you modify your design (interface view), you must update    !!
    !! the procedures corresponding to the provided interfaces in this  !!
    !! file. The up-to-date signatures can be found in the header file. !!
*/
#include "datapool.h"

#define VALUE_COUNT (2)
#define bad_name "X"

asn1SccParameterValue values[VALUE_COUNT];

void datapool_startup(void)
{
    values[0].val.kind = ParameterValue_val_paramU8_PRESENT;
    values[0].val.u.paramU8 = 16;

    values[1].val.kind = ParameterValue_val_paramF_PRESENT;
    values[1].val.u.paramF = 3.14f;
}

void datapool_PI_read_param
      (const asn1SccParameterID *IN_pid,
       asn1SccParameterValue *OUT_val,
       asn1SccFlag8 *OUT_r)

{
    for (uint32_t i = 0; i < VALUE_COUNT; i++)
    {
        if (values[i].val.kind == *IN_pid)
        {
            *OUT_val = values[i];
            *OUT_r = true;
            return;
        }
    }
    *OUT_r = false;
}


void datapool_PI_write_param
      (const asn1SccParameterValue *IN_val,
       asn1SccFlag8 *OUT_r)

{
    for (uint32_t i = 0; i < VALUE_COUNT; i++)
    {
        if (values[i].val.kind == IN_val->val.kind)
        {
            values[i].val.u = IN_val->val.u;
            *OUT_r = true;
            return;
        }
    }
    *OUT_r = false;
}


