/* Header file for function DataPool
 * Generated by TASTE (kazoo/templates/glue/language_wrappers/vm_if-header/function.tmplt)
 * DO NOT EDIT THIS FILE, IT WILL BE OVERWRITTEN DURING THE BUILD
 */

/* The purpose of this file is to provide a wrapper around the user code,
 * with a single interface that is independent of the implementation language
 * of the function. The parameters of each PI are blackboxes encoded
 * in the form specified in the interface view (Native, uPER, or ACN)
*/

#pragma once
#if defined(__unix__) || defined (__MSP430__)
   #include <stdlib.h>
   #include <stdio.h>
#else
   typedef unsigned size_t;
#endif

#include "C_ASN1_Types.h"
#include <stdio.h>
extern long long getTimeInMilliseconds(void);
#ifdef __cplusplus
extern "C" {
#endif

#include "datapool.h"

// Function initialization - calls user startup code of all dependent functions
void init_datapool(void);


/* Provided interfaces */
void datapool_read_param
      (const char *IN_pid, size_t IN_pid_len,
       char *OUT_val, size_t *OUT_val_len,
       char *OUT_r, size_t *OUT_r_len);



void datapool_write_param
      (const char *IN_val, size_t IN_val_len,
       char *OUT_r, size_t *OUT_r_len);


#ifdef __cplusplus
}
#endif

