/* Body file for function DataPool
 * Generated by TASTE (kazoo/templates/glue/language_wrappers/vm-if-body/function.tmplt)
 */
#include "datapool_vm_if.h"
#include "routing.h"

// Define a global PID variable used to keep track of the sender of the last message
static asn1SccPID sender_pid = PID_env;

// API to provide to the user code the PID of the last PI caller
void datapool_get_sender(asn1SccPID *OUT_sender_pid, asn1SccPID unused)
{
  *OUT_sender_pid = sender_pid;
}



extern void adainit(void);

unsigned datapool_initialized = 0;
void init_datapool(void)
{
   if (0 == datapool_initialized) {
      // Initialize epoch for the MSC tracing in debug mode
      long long unused __attribute__((unused)) = getTimeInMilliseconds();
      datapool_initialized = 1;
      // Call user code startup function
      extern void datapool_startup(void);
      datapool_startup();
      puts ("[TASTE] Initialization completed for function DataPool");
      datapool_initialized = 2;
   }
}
void datapool_read_param
      (const char *IN_pid, size_t IN_pid_len,
       char *OUT_val, size_t *OUT_val_len,
       char *OUT_r, size_t *OUT_r_len)

{
   sender_pid = datapool_read_param_get_sender();
   // In Debug mode and x86 builts only: log MSC data when environment variable is set
   static int innerMsc = -1;
   if (-1 == innerMsc)
     innerMsc = (NULL != getenv("TASTE_INNER_MSC"))?1:0;
   if (1 == innerMsc) {
      long long msc_time = getTimeInMilliseconds();
      printf ("INNER_PI: datapool,read_param,%lld\n", msc_time);
      fflush(stdout);
   }
   
   static asn1SccParameterID IN_PID;
   int pid_error_code = 0;
   asn1SccParameterID_Initialize(&IN_PID);

   if (0 != Decode_ACN_ParameterID (&IN_PID, (void *)IN_pid, IN_pid_len, &pid_error_code)) {
      puts("Error decoding ParameterID in function DataPool_read_param");
      return;
   }
   
   static asn1SccParameterValue OUT_VAL;
asn1SccParameterValue_Initialize(&OUT_VAL);
   
   static asn1SccFlag8 OUT_R;
asn1SccFlag8_Initialize(&OUT_R);

   //  Declare user code function as external (it may not have a .h if it is in Ada)
   extern void datapool_PI_read_param
      (const asn1SccParameterID *,
       asn1SccParameterValue *,
       asn1SccFlag8 *);





   // Call user code
   datapool_PI_read_param (&IN_PID, &OUT_VAL, &OUT_R);

   int val_error_code = 0;
   *OUT_val_len = Encode_ACN_ParameterValue
      ((void *)OUT_val,
       asn1SccParameterValue_REQUIRED_BYTES_FOR_ACN_ENCODING,
       &OUT_VAL,
       &val_error_code);
   int r_error_code = 0;
   *OUT_r_len = Encode_ACN_Flag8
      ((void *)OUT_r,
       asn1SccFlag8_REQUIRED_BYTES_FOR_ACN_ENCODING,
       &OUT_R,
       &r_error_code);
}




void datapool_write_param
      (const char *IN_val, size_t IN_val_len,
       char *OUT_r, size_t *OUT_r_len)

{
   sender_pid = datapool_write_param_get_sender();
   // In Debug mode and x86 builts only: log MSC data when environment variable is set
   static int innerMsc = -1;
   if (-1 == innerMsc)
     innerMsc = (NULL != getenv("TASTE_INNER_MSC"))?1:0;
   if (1 == innerMsc) {
      long long msc_time = getTimeInMilliseconds();
      printf ("INNER_PI: datapool,write_param,%lld\n", msc_time);
      fflush(stdout);
   }
   
   static asn1SccParameterValue IN_VAL;
   int val_error_code = 0;
   asn1SccParameterValue_Initialize(&IN_VAL);

   if (0 != Decode_ACN_ParameterValue (&IN_VAL, (void *)IN_val, IN_val_len, &val_error_code)) {
      puts("Error decoding ParameterValue in function DataPool_write_param");
      return;
   }
   
   static asn1SccFlag8 OUT_R;
asn1SccFlag8_Initialize(&OUT_R);

   //  Declare user code function as external (it may not have a .h if it is in Ada)
   extern void datapool_PI_write_param
      (const asn1SccParameterValue *,
       asn1SccFlag8 *);





   // Call user code
   datapool_PI_write_param (&IN_VAL, &OUT_R);

   int r_error_code = 0;
   *OUT_r_len = Encode_ACN_Flag8
      ((void *)OUT_r,
       asn1SccFlag8_REQUIRED_BYTES_FOR_ACN_ENCODING,
       &OUT_R,
       &r_error_code);
}

