/* ASN.1 System configuration file for function Controller
 * Generated by TASTE (kazoo/templates/glue/language_wrappers/system_config/function.tmplt)
 */

#define __NEED_T_UInt32_NATIVE
#define __NEED_T_UInt32_NATIVE


#define __NEED_Float32_NATIVE
#define __NEED_Float32_NATIVE
#define __NEED_Float32_NATIVE


#define __NEED_ParameterID_ACN
#define __NEED_ParameterValue_ACN
#define __NEED_Flag8_ACN




#define __NEED_ParameterValue_ACN
#define __NEED_Flag8_ACN
