/* Body file for function Controller
 * Generated by TASTE (kazoo/templates/glue/language_wrappers/vm-if-body/function.tmplt)
 */
#include "controller_vm_if.h"
#include "routing.h"

// Define a global PID variable used to keep track of the sender of the last message
static asn1SccPID sender_pid = PID_env;

// API to provide to the user code the PID of the last PI caller
void controller_get_sender(asn1SccPID *OUT_sender_pid, asn1SccPID unused)
{
  *OUT_sender_pid = sender_pid;
}



extern void adainit(void);

extern void init_datapool(void);
extern unsigned datapool_initialized;
extern void init_utilities(void);
extern unsigned utilities_initialized;
unsigned controller_initialized = 0;
void init_controller(void)
{
   if (0 == controller_initialized) {
      // Initialize epoch for the MSC tracing in debug mode
      long long unused __attribute__((unused)) = getTimeInMilliseconds();
      controller_initialized = 1;
      // Call user code startup function
      extern void controller_startup(void);
      controller_startup();
      puts ("[TASTE] Initialization completed for function Controller");
      controller_initialized = 2;
   }
}
void controller_activate(void)
{
   sender_pid = controller_activate_get_sender();
   // In Debug mode and x86 builts only: log MSC data when environment variable is set
   static int innerMsc = -1;
   if (-1 == innerMsc)
     innerMsc = (NULL != getenv("TASTE_INNER_MSC"))?1:0;
   if (1 == innerMsc) {
      long long msc_time = getTimeInMilliseconds();
      printf ("INNER_PI: controller,activate,%lld\n", msc_time);
      fflush(stdout);
   }

   //  Directly call user code, no parameters to pass
   extern void controller_PI_activate(void);
   controller_PI_activate();
   // puts ("controller_activate called");
}




void controller_deactivate(void)
{
   sender_pid = controller_deactivate_get_sender();
   // In Debug mode and x86 builts only: log MSC data when environment variable is set
   static int innerMsc = -1;
   if (-1 == innerMsc)
     innerMsc = (NULL != getenv("TASTE_INNER_MSC"))?1:0;
   if (1 == innerMsc) {
      long long msc_time = getTimeInMilliseconds();
      printf ("INNER_PI: controller,deactivate,%lld\n", msc_time);
      fflush(stdout);
   }

   //  Directly call user code, no parameters to pass
   extern void controller_PI_deactivate(void);
   controller_PI_deactivate();
   // puts ("controller_deactivate called");
}




void controller_pps(void)
{
   // In Debug mode and x86 builts only: log MSC data when environment variable is set
   static int innerMsc = -1;
   if (-1 == innerMsc)
     innerMsc = (NULL != getenv("TASTE_INNER_MSC"))?1:0;
   if (1 == innerMsc) {
      long long msc_time = getTimeInMilliseconds();
      printf ("INNER_PI: controller,pps,%lld\n", msc_time);
      fflush(stdout);
   }

   //  Directly call user code, no parameters to pass
   extern void controller_PI_pps(void);
   controller_PI_pps();
   // puts ("controller_pps called");
}

